import type { AccountMapping, MappingRule } from '../../shared/types';

export interface ComposeConfig {
  accessUrl: string;
  wealthfolioApiUrl: string;
  accountMapping: AccountMapping;
  syncSchedule: string;
  lookbackDays: number;
  mappingRules: MappingRule[];
}

export function generateEnvFile(config: ComposeConfig): string {
  return [
    '# SimpleFin Sync — generated by Wealthfolio addon',
    '# ⚠️  Add this file to .gitignore — NEVER commit it to git',
    '',
    `SIMPLEFIN_ACCESS_URL=${config.accessUrl}`,
    `WEALTHFOLIO_API_URL=${config.wealthfolioApiUrl}`,
    `ACCOUNT_MAPPING=${JSON.stringify(config.accountMapping)}`,
    `SYNC_SCHEDULE=${config.syncSchedule}`,
    `LOOKBACK_DAYS=${config.lookbackDays}`,
    `MAPPING_RULES=${JSON.stringify(config.mappingRules)}`,
  ].join('\n');
}

export function generateComposeSnippet(_config: ComposeConfig): string {
  return `services:
  simplefin-sync:
    image: ghcr.io/wealthfolio-community/simplefin-sync:latest
    restart: unless-stopped
    env_file: simplefin-sync.env
    networks:
      - wealthfolio_default
    user: "1000:1000"

networks:
  wealthfolio_default:
    external: true`;
}
