import type { AccountMapping, MappingRule } from '../../shared/types';

export interface ComposeConfig {
  wealthfolioApiUrl: string;
  accountMapping: AccountMapping;
  syncSchedule: string;
  lookbackDays: number;
  mappingRules: MappingRule[];
}

export function generateEnvFile(config: ComposeConfig): string {
  return [
    '# SimpleFin Sync — generated by Wealthfolio addon',
    '#',
    '# SIMPLEFIN_SETUP_TOKEN: get a NEW setup token from your SimpleFin Bridge',
    '# account page (https://beta-bridge.simplefin.org) and paste it below.',
    '# The token is one-time-use: on first start the service exchanges it for',
    '# an access URL and stores that in its Docker volume — your bank credentials',
    '# never live in this file. After the first successful start you can delete',
    '# the token line entirely.',
    'SIMPLEFIN_SETUP_TOKEN=',
    '',
    `WEALTHFOLIO_API_URL=${config.wealthfolioApiUrl}`,
    '',
    '# WEALTHFOLIO_PASSWORD: your Wealthfolio login password. Required if your',
    '# instance has authentication enabled (you see a login screen); leave',
    '# empty otherwise.',
    'WEALTHFOLIO_PASSWORD=',
    `ACCOUNT_MAPPING=${JSON.stringify(config.accountMapping)}`,
    `SYNC_SCHEDULE=${config.syncSchedule}`,
    `LOOKBACK_DAYS=${config.lookbackDays}`,
    `MAPPING_RULES=${JSON.stringify(config.mappingRules)}`,
    'STATE_FILE=/data/state.json',
  ].join('\n');
}

export function generateComposeSnippet(_config: ComposeConfig): string {
  return `services:
  simplefin-sync:
    # Built locally from the addon repo — there is no published image.
    # Copy the repo's companion/ and shared/ folders into ./simplefin-sync
    # next to this compose file first (see step 1).
    build:
      context: ./simplefin-sync
      dockerfile: companion/Dockerfile
    restart: unless-stopped
    env_file: simplefin-sync.env
    volumes:
      - simplefin-sync-data:/data
    networks:
      - wealthfolio_default
    user: "1000:1000"

volumes:
  simplefin-sync-data:

networks:
  wealthfolio_default:
    external: true`;
}
